### ISSUE TITLE
Issue to trigger new releases

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJModels.jl#263]
@JuliaRegistrator register()

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
Release notes: https://github.com/alan-turing-institute/MLJModels.jl/pull/362

**Comment by ablaom** [comment]
@JuliaRegistrator register

https://github.com/alan-turing-institute/MLJModels.jl/pull/366

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- [x] Extend compatibility requirement for MLJBase to ^0.17.1, ^0.18

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- [x] (**enhancment**) Add the following BetaML models to the registry: `GMMClusterer`, `KMeans`, `KMedoids`, `KernelPerceptronClassifier`, `MissingImputator`, `PegasosClassifier`, `PerceptronClassifier` (#376, https://github.com/alan-turing-institute/MLJ.jl/issues/749)

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- extend MLJModelInterface compat to incude 1.0

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] (**enhancement**) Add the `TSVDTransformer` model for dimension reduction via truncated singular value decomposition, as implemented in TSVD.jl. Sparse matrix input features are supported.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] (**enhancement**) Add the `TSVDTransformer` model for dimension reduction via truncated singular value decomposition, as implemented in TSVD.jl. Sparse matrix input features are supported.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [ ] Update registry to reflect expanded set of traits (#397, https://github.com/JuliaAI/StatisticalTraits.jl/pull/18)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x]  Add support for outlier detection models with an enhancement of `BinaryThresholdPredictor` #400

**Comment by ablaom** [comment]
cc @davnn

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] Add to the registry models from OutlierDetectionNearest.jl, OutlierDetectionNetworks.jl, OutlierDetectionPython.jl (#404)

**Comment by ablaom** [comment]
cc @davnn

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- Add MLJText.jl model `TfdifTransformer` to the model registry (#413)

**Comment by ablaom** [comment]
release notes:

- (**mildly breaking**) Remove MLJBase as a dependency, adding CategoricalDistributions instead (#416)
- Bump compatibility requirements of StatisticalTraits.jl and ScientificTypes.jl (changes owner of `info` method) (#417) 
- (**new models**) Add the following new models to the registry from MLJText.jl: `BM25Transformer`, `BagOfWordsTransformer` (#419)
- (**breaking**) Dissallow use of `wrapped_model=...` in `BinaryThresholdPredictor` and remove deprecation warning. Correct syntax is `BinaryThresholdPredictor(model=...)` or `BinaryThresholdPredictor(model, ...)`  (#421)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- Update registry to reflect a renaming of MLJText model `BagOfWordsTransformer` -> `CountTransformer`

**Comment by ablaom** [comment]
cc @pazzo83

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- Update registry to reflect a renaming of MLJText model `BagOfWordsTransformer` -> `CountTransformer`

**Comment by ablaom** [comment]
(second try because Requires was not correctly removed)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Add detailed, MLJ-compliant doc-strings to all transformers (#443)
- (**enhancement**) Add new method `doc(modelname::String, pkg::String=...)` to retrieve a model type doc-string from the model registry metadata, without having to load the model code (#442)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**new model**) Add `OneRuleClassifier` from [OneRule.jl](https://github.com/roland-KA/OneRule.jl) to the model registry. Do `using MLJModels; doc("OneRuleClassifier")` for details (#455) @roland-KA

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Allow `OneHotCoder` to provide basic `missing` value support by propagating missing values (#457) @Chandu-4444 
- (**bug fix**) Allow models internally implementing a ["data front-end"](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#Implementing-a-data-front-end), such as `EvoTrees` models, to behave correctly when wrapped by `BinaryThresholdPredictor(model=...)` (#459) @OkonSamuel 
- Have `matching(X, y)` issue a warning if `y` is a table with just one column (#460) @DilumAluthge 
- Bump Julia requirement to 1.6

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Update the model registry. This will make many new document strings available via `doc("SomeModel", pkg="SomePkg")`. It also add the following BetaML.jl models: `BetaMLGMMImputer`, `BetaMLGMMRegressor`, `BetaMLGenericImputer`, `BetaMLMeanImputer`, `BetaMLRFImputer`.
- Fix a bug with OneHotEncoder (#468) @olivierlabayle

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Add Clustering.jl model, `DBSCAN` to the model registry

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Add `InteractionTransformer` for generating polynomial features (#478) @olivierlabayle 
- Add `InteractionTransformer` and `HierarchicalClusterer` (from Clustering.jl) to model registry

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**new model**) Add `EvoLinearRegressor`, from  EvoLinear.jl,  to the model registry.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

- update registry to reflect new names for BetaML.jl models, and to include new docstrings from MLJText.jl (#485)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**breaking**) Modify the output of `fitted_params` for the following models, to bring the format into line with other MLJ models: `Standardizer`, `Discretizer`, `OneHotEncoder`. See the updated doc-strings for the new format (#444, PR #490)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

(**new model**) Add `SelfOrganizingMap` from SelfOrganizingMaps.jl` to the model registry.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**new models**) Add CatBoost.jl to the model regsitry, which provides these new models: `CatBoostRegressor` and `CatBoostClassifier`. 
- (**new models**) Update the registry to reflect addition of these models to OutlierDetectionPtyhon.jl 0.2.1: `INNEDetector`, `ECODDetector`, `KDEDetector`, `GMMDetector`.
- Update the registry to reflect a change in the `package_name` trait for all MLJScikitLearnInterface.jl models, from "ScikitLearn" to "MLJScikitLearnInterface" (ScikitLearn.jl is not a dependency of MLJScikitLearnInterface.jl v0.4.0.)
- (**docs**) Update the registry to reflect new and improved dcostrings for NearestNeighborModels.jl.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by OkonSamuel** [comment]
@JuliaRegistrator register branch=master

**Comment by OkonSamuel** [comment]
@JuliaRegistrator register branch=master

**Comment by OkonSamuel** [comment]
@JuliaRegistrator register branch=master

**Comment by OkonSamuel** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**new model**) Add partitioned least squares model, `PartLS`, from PartitionedLS.jl, to the model registry (#553)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**mildly breaking**) The `FeatureSelector` appearing in the Model Registry (as inspected using `models()`) is now provided by the FeatureSelection.jl package (`pkg = FeatureSelection`) instead of the MLJModels.jl package. This reflects a code migration, not a change in behaviour of the model. The only foreseeable breakage is any code with a call like `@load FeatureSelection pkg=MLJModels`; which was always redundant anyway, because the model never required explicit loading in MLJ.

- (**new models**) Add the `RecursiveFeatureElimination` model wrapper to the model registry (this will be a built-in model in next MLJ release). 

- (**new feature**) Model wrappers, such `TunedModel`, `BalancedModel` and `IteratedModel`, can now be listed using `models(...; wrappers=true)`.

- (**internals**) The `name` of a model in the Model Registry now reflects the name a model constructor instead of a model type (which are the same for all current models that aren't composite models aka, model wrappers). Model wrappers (or other models with contractor names different from the type) must overload a new trait `MLJModelInterface.constructor` to define the constructor for each type. For example, we now have `constructor(::DeterministicTunedModel) = TunedModel`. For more on this, see #558.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

-  (**new models**) Add `AffinityPropagation` from Clustering.jl to the MLJ model registry
- (**new models**) Add `LaplaceClassifier`, `LaplaceRegressor` from LaplaceRedux.jl

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master 

Release notes:

- (**new models**) Add `MaxnetBinaryClassifier` from Maxnet.jl
- (**new models**) Add = `SRTestRegressor`, `MultitargetSRTestRegressor` from SymbolicRegression.jl

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Remove the model registry tools rendered redundant by the external package MLJModelRegistryTools (#590)

- (**breaking**) Remove the following models now provided by MLJTransforms.jl instead: `ContinuousEncoder`, `FillImputer`, `InteractionTransformer`, `OneHotEncoder`, `Standardizer`, `UnivariateBoxCoxTransformer`, `UnivariateDiscrcetizer`, `UnivariateFillImputer`, `UnivariateStandardizer`, `UnivariateTimeTypeToContinuous`. (#592)

- (**new models**) Update the Model Registry to include the models provided by MLJTransforms, which includes the following completely new models: `FrequencyEncoder`, `TargetEncoder`, `CardinalityReducer`, `OrdinalEncoder`, `MissingnessEncoder`, `ContrastEncoder` (#592)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) The dummy regressor, `DeterministicConstantRegressor`, now supports multi-targets (matrices or tables).

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

-  Update the MLJ Model Registry to include latest model metadata, including accounting for migration of several models from MLJModels.jl to MLJTransforms.jl.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**new model**) The [`Freezable` wrapper](https://github.com/JuliaAI/MLJBase.jl/pull/1048) has been added to the MLJ Model Registry.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master
