### ISSUE TITLE
[tracking] PyCall -> PythonCall transition 

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJModels.jl#506]
In discussions with @tylerjthomas, @OkonSamuel and others, we have a tentative plan to transition model-providing packages that use PyCall to ones that use PythonCall instead. Unfortunately, loading packages that use *both* simultaneously, while possible, requires interventions beyond the average user (in my view) and complicates integration tests and updating the MLJ Model Registry. So this needs to be a coordinated transition.

A tentative plan is:

- [x] finalise a PythonCall branch for MLJScikitLearnInterface.jl (which also drops ScikitLearn.jl as dependency): https://github.com/JuliaAI/MLJScikitLearnInterface.jl/pull/56 
- [x] finalise a PythonCall branch for OutlierDetectionPython: https://github.com/OutlierDetectionJL/OutlierDetectionPython.jl/pull/3
- [x] check for any other PyCall dependencies in packages registered in the MLJ Model Registry (@ablaom)
- [x] run tests from MLJTestIntegration, locally, based on the PythonCall branches
- [x] take several deep breaths (@ablaom)
- [x] merge the MLJScikitLearnInterface.jl branch into master and tag new release
- [x] merge the OutlierDetectionPython.jl branch into master and tag new release
- [x] update MLJ Model Registry, including [CatBoost.jl](https://github.com/JuliaAI/MLJModels.jl/issues/501)  and tag a new MLJModels.jl release (@ablaom)

**Comment by ablaom** [comment]
Okay. I'm taking those deep breaths now. Will roll the rest of this out (including CatBoost.jl addition to registry) after the weekend.
